name = "dhankund-api"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat_v2" ]
main = "worker.js"

[env.preview]
name = "dhankund-api-preview"
route = { pattern = "dev.api.dhankund.com/*", custom_domain = true }

[[env.preview.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "dhankund-storage-preview"

[[env.preview.send_email]]
name = "SEB"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "dhankund-crm-preview"
database_id = "FILL_ME_PREVIEW_D1_ID"

[env.production]
name = "dhankund-api"
route = { pattern = "api.dhankund.com/*", custom_domain = true }

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "dhankund-storage"

[[env.production.send_email]]
name = "SEB"

[[env.production.d1_databases]]
binding = "DB"
database_name = "dhankund-crm"
database_id = "FILL_ME_D1_DATABASE_ID"
