name = "dhankund-crm-web"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat_v2" ]
main = "worker.js"

[assets]
directory = "build/web"

[env.preview]
name = "dhankund-crm-preview"
route = { pattern = "dev.crm.dhankund.com", custom_domain = true }

[env.production]
name = "dhankund-crm"
route = { pattern = "crm.dhankund.com", custom_domain = true }
