name = "dhankund-official-site"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat_v2" ]
main = ".vercel/output/static/_worker.js/index.js"

[assets]
directory = ".vercel/output/static"

[env.preview]
name = "dhankund-official-site-preview"
route = { pattern = "dev.dhankund.com", custom_domain = true }

[[env.preview.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "dhankund-storage-preview"

[[env.preview.send_email]]
name = "SEB"

[env.production]
name = "dhankund-official-site"
route = { pattern = "dhankund.com", custom_domain = true }

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "dhankund-storage"

[[env.production.send_email]]
name = "SEB"
