name: Backup Keystore
on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | tr -d '\n\r ' | base64 --decode > upload-keystore.jks
      - name: Upload Keystore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-keystore-backup
          path: upload-keystore.jks
