name: iOS Build

on:
  workflow_dispatch: # Allows you to manually trigger this build from the GitHub Actions tab
  push:
    branches:
      - master # Automatically runs when you push code to the master branch

jobs:
  build_ios:
    name: Build iOS Unsigned IPA
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get
        working-directory: "dhankund_crm"

      - name: Create config.env file
        run: |
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" > "dhankund_crm"/config.env
          echo "AWS_S3_REGION=${{ secrets.AWS_S3_REGION }}" >> "dhankund_crm"/config.env
          echo "AWS_S3_ENDPOINT=${{ secrets.AWS_S3_ENDPOINT }}" >> "dhankund_crm"/config.env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> "dhankund_crm"/config.env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> "dhankund_crm"/config.env
          
          DSA_IOS=$(echo '${{ secrets.DSA_FIREBASE_IOS }}' | tr -d '\n' | tr -d '\r')
          echo "DSA_FIREBASE_IOS='${DSA_IOS}'" >> "dhankund_crm"/config.env
          
          CRM_IOS=$(echo '${{ secrets.CRM_FIREBASE_IOS }}' | tr -d '\n' | tr -d '\r')
          echo "CRM_FIREBASE_IOS='${CRM_IOS}'" >> "dhankund_crm"/config.env

      - name: Build iOS App (Unsigned)
        # We build without codesigning because certificates are required for a signed build
        run: flutter build ios --release --no-codesign
        working-directory: "dhankund_crm"

      - name: Package into unsigned IPA
        # This converts the compiled .app into an unsigned .ipa file suitable for sideloading
        run: |
          mkdir -p Payload
          mv 'dhankund_crm/build/ios/iphoneos/Runner.app' Payload/
          zip -qq -r Dhankund_iOS.ipa Payload
          
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dhankund_iOS_App
          path: Dhankund_iOS.ipa
