name: Android APK Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'DSA-Banker-flutter app'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Create config.env file
        run: |
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" > config.env
          echo "AWS_S3_REGION=${{ secrets.AWS_S3_REGION }}" >> config.env
          echo "AWS_S3_ENDPOINT=${{ secrets.AWS_S3_ENDPOINT }}" >> config.env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> config.env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> config.env
          
          DSA_ANDROID=$(echo '${{ secrets.DSA_FIREBASE_ANDROID }}' | tr -d '\n' | tr -d '\r')
          echo "DSA_FIREBASE_ANDROID='${DSA_ANDROID}'" >> config.env
          
          CRM_ANDROID=$(echo '${{ secrets.CRM_FIREBASE_ANDROID }}' | tr -d '\n' | tr -d '\r')
          echo "CRM_FIREBASE_ANDROID='${CRM_ANDROID}'" >> config.env

      - name: Setup Keystore
        run: |
          echo "${{ secrets.DSA_KEYSTORE_BASE64 }}" | tr -d '\n\r ' | base64 --decode > android/app/upload-keystore.jks
          echo "storePassword=${{ secrets.DSA_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.DSA_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.DSA_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Build APK
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: 'DSA-Banker-flutter app/build/app/outputs/flutter-apk/app-release.apk'
